### PR TITLE
[Minor] Advanced tokens for input component

### PR DESCRIPTION
**Pull request by marcialfps**
New advanced tokens in input text component.

### CODE REVIEW

**Review by aweell — COMMENTED** [review]
## Suggestions

* Should we provide tokens for suffix and prefix icon sizes?
* I think would be interesting to provide tokens to customize the input underline
* Is the error color affecting the "*" of the required fields? Should we provide tokens to change the size, weight and color?

**Comment by marcialfps** [comment]
> ## Suggestions
> * Should we provide tokens for suffix and prefix icon sizes?
These tokens were added but I discarded them because user can break the component. 
Example:
image

> * I think would be interesting to provide tokens to customize the input underline
The input underline uses fontColorBase to apply a color, maybe we can create a new specific token when the user wants a different color for the underline. Apart from this token, could it be interesting to add a thickness token?

> * Is the error color affecting the "*" of the required fields? Should we provide tokens to change the size, weight and color?
No. The error color is only for the error status, not for the required status.

**Comment by aweell** [comment]
We can add the following then:

* `underlineColor`
* `underlineFocusColor`
* `underlineThickness`
* `requiredMarkColor`
* `requiredMarkFontWeight`
* `requiredMarkFontSize`

**Comment by marcialfps** [comment]
> We can add the following then:
> 
> * `underlineColor`
> * `underlineFocusColor`
> * `underlineThickness`

:thumbsup:

> * `requiredMarkColor`
> * `requiredMarkFontWeight`
> * `requiredMarkFontSize`

The Required mark is a common component (DxcRequired) shared with Checkbox, Radio, Select, Switch and Textarea. If we want to add these tokens we need to separate this component for each case or create a new public component that can be tokenised.

**Review by aweell — COMMENTED** [review]
@jsardid can you give your input about this?

> The Required mark is a common component (DxcRequired) shared with Checkbox, Radio, Select, Switch and Textarea. If we want to add these tokens we need to separate this component for each case or create a new public component that can be tokenised.

**Pull request merged**
