### PR TITLE
[Minor] Fixing dialog doc padding default value

### PR DESCRIPTION
**Pull request by Jialecl**
It seems that when no padding was used, the component was using spaces["small"] as the default value.
The documentation has been updated to reflect that.

### CODE REVIEW

**Comment by GomezIvann** [comment]
Why are we adding a default value for padding? The same scenario happens in the Accordion component and it doesn't have a value by default.

**Comment by Jialecl** [comment]
> Why are we adding a default value for padding? The same scenario happens in the Accordion component and it doesn't have a value by default.


The default value used in the css is spaces["small"].
This is the same as having small padding as default.

padding: ${(props) =>
      props.padding && typeof props.padding !== "object" ? spaces[props.padding] : spaces["small"]};

**Comment by GomezIvann** [comment]
> > Why are we adding a default value for padding? The same scenario happens in the Accordion component and it doesn't have a value by default.
> 
> The default value used in the CSS is spaces["small"]. This is the same as having small padding as default.
> 
> padding: ${(props) => props.padding && typeof props.padding !== "object" ? spaces[props.padding] : spaces["small"]};
> 
> I think this should be documented as such.

My question goes a bit further, why it was set as `small` by default? I don't think we should establish a default padding, what do you think @aweell?

**Comment by Jialecl** [comment]
I understand your concerns but I think that can be a different discussion. 
This change is aimed to update the documentation to reflect how the component is working now.

**Comment by GomezIvann** [comment]
> My question goes a bit further, why it was set as `small` by default? I don't think we should establish a default padding, what do you think @aweell?

Totally agree with this Jiale!

**Review by GomezIvann — APPROVED** [review]

**Pull request merged**
