### PR TITLE
Add Pull Request template

### PR DESCRIPTION
**Pull request by marcialfps**
**Checklist**
_(Check off all the items before submitting)_
- [x] Build process is done without errors and all tests pass in `/lib` directory.
- [x] Self-reviewed the code prior to submitting.
- [x] Meets accessibility standards.
- [x] Added/updated documentation to `/website` as needed.
- [x] Added/updated tests as needed.

**Purpose**
The purpose of this change is to improve PR reviews through well-explained descriptions.

**Description**
Now we require to complete a checklist before creating a pull request. Also, descriptions, screenshots, context, and issue numbers are included in the default template.

**Screenshots**
image

**Additional context**
No needed.

**Closes #test**

### CODE REVIEW

**Review by kukoc — DISMISSED** [review]
LGTM

**Comment by GomezIvann** [comment]
The description is used to summarize the work/changes that have been done, but, what about the **purpose** of a pull? Maybe we need an additional section to describe the purpose behind the pull request, since not all should have an issue associated and I don't think this topic fits in any of the proposed sections.

**Comment by kukoc** [comment]
> purpose

the purpose of a PR shouldn't it be described and discussed in the linked issue?

**Comment by marcialfps** [comment]
> > but, what about the purpose of a pull
> 
> the purpose of a PR shouldn't it be described and discussed in the linked issue?

That is a good point. Should we always have an issue linked to a PR? 

Maybe we can have some cases where the changes are too small and we don't need to create an issue.

**Comment by GomezIvann** [comment]
> > but, what about the purpose of a pull
> 
> the purpose of a PR shouldn't it be described and discussed in the linked issue?

Not necessarily. A pull may not have a linked issue, that's the point.

**Comment by marcialfps** [comment]
Added purpose section: 
image

**Review by GomezIvann — APPROVED** [review]

**Review by raquelarrojo — APPROVED** [review]

**Pull request merged**
