### PR TITLE
Added spinner stories

### PR DESCRIPTION
**Pull request by Lisa159**

### CODE REVIEW

**Comment by raquelarrojo** [comment]
We could add a test for small mode with value.

**Comment by raquelarrojo** [comment]
We also need a dark example.

**Comment by Lisa159** [comment]
> We could add tests for both modes with value 100% to see the entire spinner, and other with other values. Remove the tests without value because the snapshots are going to change all the times.

Done

**Comment by Lisa159** [comment]
> We also need dark examples.

Overlay mode should be the dark examples.

**Review by raquelarrojo — APPROVED** [review]

**Pull request merged**
