### PR TITLE
Added Tabs stories

### LINKED ISSUE #545: Add visual regression tests for Tabs component

### PR DESCRIPTION
**Pull request by marcialfps**
Closes #545

### CODE REVIEW

**Comment by Lisa159** [comment]
Disabled tabs should not have focus, hover or active styling, maybe opening an issue with this?

**Comment by marcialfps** [comment]
> Disabled tabs should not have focus, hover or active styling, maybe opening an issue with this?

I'm not sure. What do u think @aweell ? 🤔

**Comment by aweell** [comment]
> > Disabled tabs should not have focus, hover or active styling, maybe opening an issue with this?
> 
> 
> 
> I'm not sure. What do u think @aweell ? 🤔 

I agree with @Lisa159, disabled tabs doesn't allow interaction; ergo, none of the :pseudo-classes apply when the tab is in this state.

**Comment by marcialfps** [comment]
Opened issue #652

**Review by Lisa159 — APPROVED** [review]

**Pull request merged**
