### PR TITLE
[Minor] Advanced tokens for Textarea component

### PR DESCRIPTION
**Pull request by GomezIvann**
Added advanced tokens for the Textarea component. They had also been implemented and tested. This includes the theme-builder previews.

### CODE REVIEW

**Review by aweell — COMMENTED** [review]
With which tokens can the font properties of the text area content be changed?

**Comment by GomezIvann** [comment]
> With which tokens can the font properties of the text area content be changed?

With none of them. Should i implement specific tokens for the content or synchronise them with those of the label?

**Review by aweell — COMMENTED** [review]
I think it would be better to create the `customContent...` tokens that we have already in other components

**Review by aweell — APPROVED** [review]
👍🏼

**Pull request merged**
